// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnH45eFxB0Ra5quVuUkYqeVDIV-Lbdha4',
    appId: '1:156613201236:web:b1392fa426f20d16dfccc1',
    messagingSenderId: '156613201236',
    projectId: 'street-food-explorer-c22fd',
    authDomain: 'street-food-explorer-c22fd.firebaseapp.com',
    storageBucket: 'street-food-explorer-c22fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOsbvrAZMSQ2_uMfxE3e6dOiKHKSINPc',
    appId: '1:156613201236:android:109a6582968028e0dfccc1',
    messagingSenderId: '156613201236',
    projectId: 'street-food-explorer-c22fd',
    storageBucket: 'street-food-explorer-c22fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6WBL_Q0wCI9rFhY-cILGKbXWBsD0g9w',
    appId: '1:156613201236:ios:0b7f5437b5c54675dfccc1',
    messagingSenderId: '156613201236',
    projectId: 'street-food-explorer-c22fd',
    storageBucket: 'street-food-explorer-c22fd.firebasestorage.app',
    iosBundleId: 'com.example.streetFoodExplorer',
  );
}
